apiVersion: v1

kind: Service

metadata:
name: frontend-service

spec:

type: LoadBalancer

selector:
app: frontend

ports:

* port: 80
  targetPort: 3000
  EOF

cat << 'EOF' > jenkins/Jenkinsfile
pipeline {

agent any

stages {

stage('Checkout'){
steps{
checkout scm
}
}

stage('Build'){
steps{
sh 'docker build -t frontend app/frontend'
}
}

stage('Terraform'){
steps{
sh '''
cd terraform
terraform init
terraform apply -auto-approve
'''
}
}

stage('Deploy'){
steps{
sh 'kubectl apply -f k8s/'
}
}

}

}
